image: python:3.8.5

pipelines:
  default:
    - parallel:
      - step:
          name: Django Company API tests
          caches:  # cached, bcs otherwise we would have to donwload each time
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest coronavstech -s -v --durations=0 -m "not skip_in_ci"
            
      # - step:
      #     name: Fibonacci tests
      #     caches:
      #       - pip
      #     script:
      #       - pip install pipenv --upgrade
      #       - pipenv install --system
      #       - pytest fibonacci/ -s -v --durations=0 --cov=.
